function getCart(){return JSON.parse(localStorage.getItem("cart")||"[]")}
function saveCart(cart){localStorage.setItem("cart",JSON.stringify(cart));updateCartCount()}
function updateCartCount(){const n=getCart().reduce((s,i)=>s+i.qty,0);document.querySelectorAll(".cart-count").forEach(e=>e.textContent=n)}
function stars(n){return "⭐".repeat(n)+"☆".repeat(5-n)}
function productCard(p){return `<div class="product-card"><a href="product-details.html?id=${p.id}"><div class="product-image"><span class="discount">-${p.discount}%</span><div class="product-placeholder">${p.icon}</div></div></a><div class="product-info"><p class="product-category">${p.category}</p><h3>${p.name}</h3><div class="rating">${stars(p.rating)}</div><div class="price"><span class="current-price">$${p.price}</span><span class="old-price">$${p.oldPrice}</span></div><button class="add-cart" onclick="addToCart(${p.id})">Add To Cart</button></div></div>`}
function renderFeaturedProducts(){const el=document.getElementById("featured-products");if(el)el.innerHTML=products.slice(0,4).map(productCard).join("");updateCartCount()}
function renderProductsPage(){const grid=document.getElementById("all-products"),search=document.getElementById("searchInput"),filter=document.getElementById("categoryFilter");let params=new URLSearchParams(location.search);if(params.get("category"))filter.value=params.get("category");function draw(){let q=search.value.toLowerCase(),c=filter.value;let list=products.filter(p=>(c==="All"||p.category===c)&&p.name.toLowerCase().includes(q));grid.innerHTML=list.length?list.map(productCard).join(""):'<div class="empty">No products found.</div>'}search.addEventListener("input",draw);filter.addEventListener("change",draw);draw();updateCartCount()}
function addToCart(id){let cart=getCart(),item=cart.find(i=>i.id===id);if(item)item.qty++;else cart.push({id,qty:1});saveCart(cart);alert("Product added to cart!")}
function renderProductDetails(){let id=Number(new URLSearchParams(location.search).get("id"))||1,p=products.find(x=>x.id===id)||products[0],el=document.getElementById("product-detail");el.innerHTML=`<div class="detail-card"><div class="detail-image">${p.icon}</div><div class="detail-info"><p class="section-label">${p.category}</p><h1>${p.name}</h1><div class="rating">${stars(p.rating)}</div><h2>$${p.price}</h2><p>${p.description}</p><div class="quantity"><label>Quantity <input id="qty" type="number" min="1" value="1"></label></div><button class="add-cart" onclick="addQuantity(${p.id})">Add To Cart</button></div></div>`;updateCartCount()}
function addQuantity(id){let qty=Math.max(1,Number(document.getElementById("qty").value)||1),cart=getCart(),item=cart.find(i=>i.id===id);if(item)item.qty+=qty;else cart.push({id,qty});saveCart(cart);alert("Product added to cart!")}
function renderCart(){let el=document.getElementById("cart-content"),cart=getCart();if(!cart.length){el.innerHTML='<div class="empty"><h2>Your cart is empty</h2><p>Start shopping and add some products.</p><br><a class="btn primary-btn" href="products.html">Shop Now</a></div>';updateCartCount();return}let total=0;el.innerHTML=`<div class="cart-table">${cart.map(item=>{let p=products.find(x=>x.id===item.id),sub=p.price*item.qty;total+=sub;return `<div class="cart-item"><div><strong>${p.icon} ${p.name}</strong><br><small>$${p.price} each</small></div><div><button onclick="changeQty(${p.id},-1)">−</button> ${item.qty} <button onclick="changeQty(${p.id},1)">+</button></div><div>$${sub}</div><button onclick="removeFromCart(${p.id})">❌</button></div>`}).join("")}<div class="cart-total">Total: $${total.toFixed(2)}</div><a class="btn primary-btn" href="checkout.html">Proceed to Checkout</a></div>`;updateCartCount()}
function changeQty(id,d){let cart=getCart(),i=cart.find(x=>x.id===id);if(i){i.qty+=d;if(i.qty<=0)cart=cart.filter(x=>x.id!==id)}saveCart(cart);renderCart()}
function removeFromCart(id){saveCart(getCart().filter(x=>x.id!==id));renderCart()}
function renderCheckout(){let el=document.getElementById("checkout-summary"),cart=getCart(),total=0;if(!cart.length){el.innerHTML="<p>Your cart is empty.</p>";return}el.innerHTML=cart.map(i=>{let p=products.find(x=>x.id===i.id),s=p.price*i.qty;total+=s;return `<div class="summary-row"><span>${p.name} × ${i.qty}</span><strong>$${s}</strong></div>`}).join("")+`<div class="summary-row"><strong>Total</strong><strong>$${total.toFixed(2)}</strong></div>`;document.getElementById("checkoutForm").addEventListener("submit",e=>{e.preventDefault();localStorage.removeItem("cart");alert("Order placed successfully!");location.href="index.html"});updateCartCount()}
document.addEventListener("DOMContentLoaded",updateCartCount);